apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  externalTrafficPolicy: 'Local'
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 4.159.116.108