apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  externalTrafficPolicy: 'Local'
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
  # loadBalancerIP: <Static IP>